---
- name: Configure Machine
  hosts: all
  vars:
    user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    home: "{{ ansible_env.HOME }}"

  roles:
    - common
    - shell

    # Conditional Role: Only install heavy engineering tools on the Laptop
    - role: engineering
      when: inventory_hostname == 'framework16'
