---
- name: Configure udev rules for Arduino Uno R4 (Renesas core)
  ansible.builtin.copy:
    dest: /etc/udev/rules.d/60-arduino-renesas.rules
    content: |
      # Renesas based Arduino Santiago/Portenta H33 bootloader mode UDEV rules
      SUBSYSTEMS=="usb", ATTRS{idVendor}=="2341", MODE:="0666"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - Reload udev rules
    - Trigger udev rules
