# User Details
user_name: "vwu"

# System Settings
timezone: "America/New_York"
default_shell: "/bin/zsh"

# Package Lists 
global_packages:
  core:
    - git
    - curl
    - vim
    - fastfetch
  shell_env:
    - zsh
    - stow

global_flatpaks:

stow_dirs:
  - zsh
  - nvim
  - distrobox
