---
- name: Install 1Password directly from URL
  dnf:
    name: "https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm"
    state: present
    disable_gpg_check: yes
  become: true
