---
- name: Setup Mullvad VPN
  block:
    - name: Add Mullvad VPN Repository 
      get_url:
        url: https://repository.mullvad.net/rpm/stable/mullvad.repo
        dest: /etc/yum.repos.d/mullvad.repo
        mode: '0644'

    - name: Install Mullvad VPN
      dnf:
        name: mullvad-vpn
        state: present
  become: true

