---
- name: Enable RPM Fusion Free and Nonfree repositories
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  become: true

- name: Upgrade the Fedora core group
  dnf:
    name: '@core'
    state: latest
  become: true
