---
host_packages:
  utils:
    - wget
    - htop
    - btop
  tools:
    - kicad
    - inkscape

host_flatpaks:
  daily:
    - com.slack.Slack
    - com.discordapp.Discord
    - dev.aunetx.deezer
  gaming:
    - com.valvesoftware.Steam
  tools:
    - com.bambulab.BambuStudio
