---
install_media_codecs: true
enable_amd_hw_accel: false

host_packages:
  utils:
    - wget
    - htop
    - btop
    - uv
  tools:
    - kicad
    - inkscape

host_flatpaks:
  daily:
    - com.slack.Slack
    - com.discordapp.Discord
    - dev.aunetx.deezer
  gaming:
    - com.valvesoftware.Steam
  tools:
    - cc.arduino.IDE2  
    - com.bambulab.BambuStudio
